# Homebrew

eval "$(/opt/homebrew/bin/brew shellenv)"

# Path

path=(
    ~/.local/bin
    /opt/homebrew/opt/grep/libexec/gnubin
    /opt/homebrew/opt/llvm/bin
    /opt/homebrew/opt/python@3.13/libexec/bin
    $path
)

# Environment

export CLICOLOR=1
export LC_COLLATE=C
export LSCOLORS="gxfxcxdxbxegedabagacad"

export EDITOR='vim'
export LESS="-FR"

export PYTHONBREAKPOINT=ipdb.set_trace

# Python

[[ -f ~/.venv/bin/activate ]] && source ~/.venv/bin/activate

# Completions

fpath=($(brew --prefix)/share/zsh-completions $fpath)

autoload -Uz compinit
compinit -i

# Aliases

alias ..='cd ..'
alias ...='cd ../..'
alias e='code'
alias g='grep'
alias grep='grep --color=auto'
alias l='ls -lah'
alias p='pwd -P'
alias rl='readlink'
alias rm='rm -i'
alias v='vim'

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gdh='git diff HEAD'
alias gg='git grep'
alias gl='git log'
alias gs='git status'
alias gst='git stash'

# Theme

source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
