eval "$(/opt/homebrew/bin/brew shellenv)"

path=(
    ~/.local/bin
    /opt/homebrew/opt/grep/libexec/gnubin
    /opt/homebrew/opt/llvm/bin
    /opt/homebrew/opt/python@3.13/libexec/bin
    $path
)

export EDITOR='vim'
export LC_COLLATE=C
export PYTHONBREAKPOINT=ipdb.set_trace

if type brew &>/dev/null; then
    fpath=($(brew --prefix)/share/zsh-completions $fpath)
fi

autoload -Uz compinit
compinit -i

alias ..='cd ..'
alias ...='cd ../..'
alias e='vim'
alias grep='grep --color=auto'
alias g='grep'
alias ls='ls -G'
alias l='ls -lah'
alias p='pwd -P'
alias rl='readlink'
alias rm='rm -i'

alias ga='git add'
alias gb='git branch'
alias gc='git commit'
alias gco='git checkout'
alias gd='git diff'
alias gdh='git diff HEAD'
alias gl='git log'
alias gs='git status'
alias gst='git stash'

export LSCOLORS="gxfxcxdxbxegedabagacad"

source $(brew --prefix)/share/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
